#!/usr/bin/env bash
set -x -eu -o pipefail

# bust cache for apt-get daily
CACHE_APT=$(date '+%Y-%m-%d')

# bust cache for pip when requirements.txt changes
CACHE_PIP=$(shasum -a 256 requirements.txt | cut -f1 -d' ')
CACHE_PIP_PACKER=$(shasum -a 256 packer/requirements.txt | cut -f1 -d' ')

docker build --build-arg CACHE_APT="$CACHE_APT" \
             --build-arg CACHE_PIP="$CACHE_PIP" \
             -t trussworks/circleci-docker-primary \
             -t trussworks/circleci-docker-primary:base \
             -t trussworks/circleci-docker-primary:tf12 \
             .

pushd packer
docker build --build-arg CACHE_PIP_PACKER="$CACHE_PIP_PACKER" \
             -t trussworks/circleci-docker-primary:packer \
             .
popd

pushd tf11
docker build --build-arg CACHE_PIP_PACKER="$CACHE_PIP_PACKER" \
             -t trussworks/circleci-docker-primary:tf11 \
             .
popd


pushd go
docker build --build-arg CACHE_APT="CACHE_APT" \
	     -t trussworks/circleci-docker-go \
	     -t trussworks/circleci-docker-go:base \
             -t trussworks/circleci-docker-go:tf12 \
             .
popd

pushd python
docker build --build-arg CACHE_APT="CACHE_APT" \
	     --build-arg CACHE_PIP="CACHE_PIP" \
	     -t trussworks/circleci-docker-python \
	     -t trussworks/circleci-docker-python:base \
             .
popd

pushd node
docker build --build-arg CACHE_APT="CACHE_APT" \
	     -t trussworks/circleci-docker-node \
	     -t trussworks/circleci-docker-node:base \
	     .
popd
