#!/bin/bash
set -eu -o pipefail

for tag in latest packer tf12; do
    echo "* Testing USER is properly set to 'circleci' on '$tag' tagged image"
    docker run -it trussworks/circleci-docker-primary:$tag bash -xc '[[ $(whoami) = circleci ]]'
done

echo Passed.
exit 0
