#!/usr/bin/env bash
set -x -eu -o pipefail

# bust cache for apt-get daily
CACHE_APT=$(date '+%Y-%m-%d')

# bust cache for pip when requirements.txt changes
CACHE_PIP=$(shasum -a 256 requirements.txt | cut -f1 -d' ')
CACHE_PIP_PACKER=$(shasum -a 256 packer/requirements.txt | cut -f1 -d' ')

docker build --build-arg CACHE_APT="$CACHE_APT" \
	     --build-arg CACHE_PIP="$CACHE_PIP" \
	     -t trussworks/circleci-docker-primary \
	     -t trussworks/circleci-docker-primary:base \
	     -t trussworks/circleci-docker-primary:tf13 \
	     .

pushd packer
docker build --build-arg CACHE_PIP_PACKER="$CACHE_PIP_PACKER" \
	     -t trussworks/circleci-docker-primary:packer .
popd

pushd nuker
docker build -t trussworks/circleci-docker-primary:nuker .
popd

pushd rotator
docker build -t trussworks/circleci-docker-primary:rotator .
popd

pushd tf13
docker build -t trussworks/circleci-docker-primary:tf13 .
popd

pushd ghr
docker build -t trussworks/circleci-docker-primary:ghr .
popd